### ISSUE TITLE
v4 support

### ISSUE THREAD

**Issue by sxwebdev** [feathers-plus/feathers-authentication-management#124] opened 2019-08-24 22:36 UTC
Hello. When will version 4 be supported?
The password is currently incorrectly restored.

**Comment by TheSinding** [comment] 2019-09-03 09:07
I've got it working with feathers-authentication-local v4.
See more [here](https://github.com/TheSinding/feathers-authentication-management/commit/4c4d91c14a02ff045bb40560af4875537d29e5d5).

Are you interested in me creating a pull request @eddyystop ?

**Comment by octopusOnJellyfish** [comment] 2019-09-17 13:13
> I've got it working with feathers-authentication-local v4.
> See more [here](https://github.com/TheSinding/feathers-authentication-management/tree/update-to-v4).
> 
> Are you interested in me creating a pull request @eddyystop ?
> The tests are successful, but its not backwards compatible.

Hi there, thanks for compatible version with v4.

I forked your repo and made a npm package at [authentication-local-management-v4](https://www.npmjs.com/package/authentication-local-management-v4)

**Comment by OnePunchMan007** [comment] 2019-09-26 16:31
Can you make a pull request octopus or Sinding ?

**Comment by TheSinding** [comment] 2019-09-26 17:43
Done :)

**Comment by longseespace** [comment] 2019-09-28 04:41
Not sure what's going on here but I'm using `feathers-authentication-management@2.0.1` and `@feathersjs/authentication@4.3.0` and looks like it's working fine.

Am I missing anything?

**Comment by OnePunchMan007** [comment] 2019-09-28 23:27
well i don't get it : it seems eddyystop a rewrite feathers-authentication-management
 in to authentication-local-management (https://github.com/feathers-plus/authentication-local-management). so i thinks it's better to continue with authentication-local-management?

**Comment by ikakosta** [comment] 2019-10-20 12:48
@OnePunchMan007 I'm about to start implementing verify email and password reset functionality. I'm using feathers v4. I want to choose the right package, but I can't install authentication-local-management via npm?

**Comment by OnePunchMan007** [comment] 2019-10-20 14:01
From my research it's : 
eddyystop rewrite feathers-authentication-management in to authentication-local-management but he stop working on it this january 2019 (CF : slack feathers).
And longseespace was right feathers-authentication-management (v2.0.1) is working why fethers.js v4.0. I implement it like this and it's working
what octopus and thesinding are doing it's to update dependency of feathers-authentication-management (v2.0.1) and they commit it but eddyytop is no longer wokring on it so i don't know if it will be accepted.

**Comment by TheSinding** [comment] 2019-10-20 18:34
@OnePunchMan007 
Yeah, that sounds about right

**Comment by eikaramba** [comment] 2019-11-01 17:13
yes that would be great. unfortunately eddyystop basically vanished from earth until 6 months around. hopefully he is fine, but there is no sign of him online anywhere

**Comment by eikaramba** [comment] 2019-11-01 17:22
btw: something is wrong with the repo from @octopusOnJellyfish  https://www.npmjs.com/package/authentication-local-management-v4
i get "verifiedExpires.getTime is not a function" upon calling resendVerifySignup action.
weirdly the code that is producing that error is not in the repo from @TheSinding

**Comment by eikaramba** [comment] 2019-11-01 17:44
LAstly i cannot report that current feathers-authentication-management is working fine with feathers v4. the hashpassword function is not working correctly. so when you reset your password you cannot login with the same afterwards

**Comment by eikaramba** [comment] 2019-11-01 17:52
Sry for spamming but i just like to summarize my observations:
repo from @octopusOnJellyfish (based on @TheSinding ): resetting password **is working**, resending verification link **not working** (`verifiedExpires.getTime is not a function`)
repo from @TheSinding : **not published**, cannot test
feathers-authentication-management(this): resetting password **is not working**, resending verification link **is working**
authentication-local-management (refactored from eddyystop): unfortunately not yet finished it seems

**Comment by TheSinding** [comment] 2019-11-03 14:23
@eikaramba 
I'm very busy at work lately, but I can take a look at it in a couple of weeks.

Have you tried reaching him on the #feathersjs Slack ?

**Comment by OnePunchMan007** [comment] 2019-11-17 02:56
> 
> 
> Sry for spamming but i just like to summarize my observations (not saying they are true, i admit i had weird problems while testing):
> 
>     * repo from @octopusOnJellyfish (based on @TheSinding ): resetting password **is working**, resending verification link **not working** (`verifiedExpires.getTime is not a function`)
> 
>     * repo from @TheSinding : **not published**, build it locally - **working**
> 
>     * feathers-authentication-management(3.0.0): resetting password **is not working**, resending verification link **is working**
> 
>     * feathers-authentication-management(2.0.1): **working**
> 
>     * authentication-local-management (refactored from eddyystop): unfortunately not yet finished it seems

The repo from @octopusOnJellyfish (based on @TheSinding ) is working for me

**Comment by sechel** [comment] 2020-01-29 09:16
I would find it the better solution to resume working on this official version here than putting together alternative repos and npm releases. If @eddyystop is not able to continue maintaining this we should find another maintainer who can accept pull requests and release the package to npm. What do you think? Pinging @daffl

**Comment by TheSinding** [comment] 2020-01-29 09:36
@sechel 
I agree, but as I understood it, the alternative repos were a temporary idea

**Comment by sechel** [comment] 2020-01-29 09:48
> @sechel
> I agree, but as I understood it, the alternative repos were a temporary idea

It's a good thing for the moment 👍 but in the long run it's harmful for the feathers ecosystem to have many competing packages on `npm` doing the same thing. It's confusing and makes it hard for people getting started.  
From what I understand now, something must have happened to @eddyystop in mid 2019 that made him stop working on this project and all of his others. I hope he is ok but it doesn't look good.

**Comment by TheSinding** [comment] 2020-01-29 09:54
>  but in the long run it's harmful for the feathers ecosystem to have many
competing packages on npm doing the same thing. It's confusing and makes it
hard for people getting started
Agreed

> From what I understand now, something must have happened to @eddyystop
<https://github.com/eddyystop> in mid 2019 that made him stop working on
this project and all of his others. I hope he is ok but it doesn't look
good.
Let's hope not!

Den ons. 29. jan. 2020 kl. 10.48 skrev Stefan Sechelmann <
notifications@github.com>:

**Comment by claustres** [comment] 2020-01-29 13:45
In case nobody has noticed it there was an on-going [upgrade guide](https://github.com/feathers-plus/authentication-local-management/blob/master/misc/upgrading.md) to move from https://github.com/feathers-plus/feathers-authentication-management to https://github.com/feathers-plus/feathers-authentication-management. We had some discussions with John Szwaronek (@eddyystop) about new features he would like to add in the module like inviting users, plugin architecture, etc. I hope this can help.

**Comment by OnnoGabriel** [comment] 2020-02-07 14:41
@claustres, thanks for the update. However, the "new" project https://github.com/feathers-plus/authentication-local-management is quite old with the last commit 13 months ago (i.e. before Feathers v4). The same for the upgrade guide. 

What would really help: is there any (official or at least actively maintained) package similar to feathers-authentication-management or authentication-local-management? A package that extends the basic auth functionality in Feathers with endpoints for e-mail verification, password resend and password reset? Including e-mail notifications? This is still a common work flow for many apps.

It is great that this package still runs with Feathers 4. But for how long without active maintenance? So, I agree with @sechel. The current situation is a bit confusing.

**Comment by daffl** [comment] 2020-02-07 17:04
The answer is pretty simple: This package is currently not maintained and looking for a maintainer. It is also up to whichever maintainer to decide which one of the two would be the better one to continue. If someone accepts to take it on, it will be moved to the [feathersjs-ecosystem](https://github.com/feathersjs-ecosystem) organization. There's clearly a need and it's open source so be wild.

![download](https://user-images.githubusercontent.com/338316/74049376-d53ac580-4988-11ea-84a5-dd108616b70c.jpeg)

**Comment by OnePunchMan007** [comment] 2020-02-07 17:34
i'm a beginner but i love feathers.js and i have read a lot about this package. i would be glad to help (documentation or what ever) the new maintainer

**Comment by claustres** [comment] 2020-02-27 20:20
As discussed in slack and due to the fact @eddyystop cannot work anymore on this module a couple of people will try to keep it alive. I've just started looking at current issues/PRs on this one, any help is welcome.

I will not have much time to work on the new module in the near future https://github.com/feathers-plus/authentication-local-management so that the best option is to focus here because, at least, I already know how it works in broad lines. Any volunteer to start looking at the other module ?

**Comment by OnnoGabriel** [comment] 2020-05-07 12:45
What is the status of this issue? The current version of this package does not work with Feathers 4. And the [pull request ](https://github.com/feathers-plus/feathers-authentication-management/pull/127) by @TheSinding is still pending because of a conflict, as far as I can see.

There is also a fork [feathers-authentication-management-v4](https://github.com/octopusOnJellyfish/feathers-authentication-management-v4) by @octopusOnJellyfish  based on the work of @TheSinding. I used that version already successfully with Feathers 4. Should that version be integrated back to this original package?

**Comment by claustres** [comment] 2020-05-07 13:00
As far as I remember the PR is waiting about some feedback from @TheSinding because some people reported that the module (at least the published version) works as is with Feathers v4.

This PR is probably related to the master version only, but not sure about that as I did not investigate the code in detail.

**Comment by TheSinding** [comment] 2020-05-08 20:07
My bad, i totally forgot this.

I can take a look at it, during the next week.
(I'm gonna write it down this time 😄)

**Comment by TheSinding** [comment] 2020-05-20 09:01
This should be fixed now.

**Comment by OnnoGabriel** [comment] 2020-05-25 07:20
Thanks a lot @TheSinding and @claustres. I just tried the new master branch of this package in our Feathers v4 app. Seems to be fine now!

It should be published as npm package, too.

**Comment by claustres** [comment] 2020-05-25 07:59
@OnnoGabriel I am currently discussing with the Feathers guys to get access to the NPM if possible. Another option is to move the module to our own organisation https://github.com/kalisio if we take it over and start with a new namespace like `@kalisio/feathers-authentication-management`. It might be more easy to manage access right instead of always asking someone else. I think we will be set soon, let me know of any feedback on this.

**Comment by OnnoGabriel** [comment] 2020-05-25 09:15
@claustres Both options would be fine with me, as long as it facilitates a fast and easy NPM packaging. If you move the project to `@kalisio`, will there we redirects from the old GitHub location?

**Comment by claustres** [comment] 2020-05-25 10:32
It seems to be the case https://help.github.com/en/github/administering-a-repository/transferring-a-repository. 

About the NPM packaging there are the required npm scripts already although we will need to test it because the structure has changed (no babel output anymore).

**Comment by TheSinding** [comment] 2020-05-25 10:36
I'd argue the best would be to stay in the feathers repos, since the founder of the repo was closely tied to feathers.

**Comment by claustres** [comment] 2020-05-25 13:30
According to what Daffl said to me the founder what not really "closely tied" to feathers core team, that's the reason why right management was separated between different people. He proposed to either migrate to our own organisation or possibly to move the module to https://github.com/feathersjs-ecosystem, which is more "closely tied" to feathers core team.

**Comment by TheSinding** [comment] 2020-05-25 13:33
Hrm.
What would the benefits be of moving it to https://github.com/feathersjs-ecosystem?
Better discovery ?

**Comment by claustres** [comment] 2020-05-25 13:40
I don't know if it will provide benefits except being probably more "closely tied" to feathers core team. Moving to our kalisio org is basically to have an easier access to the "management" part if we take it (GitHub, NPM, Travis, etc.) over but no more at this point. It also depends on who is able to help maintaining the repo at this stage and what is preferred to collaborate ?

**Comment by TheSinding** [comment] 2020-05-25 13:43
I wouldn't mind helping, if you need the help.
It true, it would be easier to manage it on your own repo.

I can see pros and cons of both ways.

**Comment by claustres** [comment] 2020-05-27 07:38
Closing now as the discussion is not really related to migration to v4.

**Closed by claustres** 2020-05-27 07:38 UTC

**Comment by claustres** [comment] 2020-06-05 13:46
@OnnoGabriel @TheSinding @mattyg For your information before trying to publish to NPM I updated some old dependencies like mocha or istanbul. Then I tried to lint the code and found some strange things. Notably this [line](https://github.com/feathers-plus/feathers-authentication-management/blob/master/src/reset-password.js#L76) which I commented out now but that should probably be a `throw`. However if I add this throw then a lot of tests fail, meaning that some tests are not probably written correctly. If anyone could give it a try it would help, thanks.

**Comment by TheSinding** [comment] 2020-06-05 19:51
@claustres I'll give it a look on Sunday

**Comment by OnnoGabriel** [comment] 2020-06-07 17:21
@TheSinding Please let me know if you need help or if you have no time.

**Comment by claustres** [comment] 2020-06-07 19:07
FYI @TheSinding I've just invited you as a maintainer on the repo it it helps

**Comment by TheSinding** [comment] 2020-06-08 07:03
@OnnoGabriel - I will do, had plans to do it sunday afternoon, but I had family stuff. I will see if I can get it done by today or tomorrow.

@claustres - I have accepted your invite :)

**Comment by claustres** [comment] 2020-06-19 07:42
Good news guys, I think I am done now with the tests and fixed latest issue after identifying the problem with @TheSinding, before releasing it will be great however if someone could check if it works well on his side.

**Comment by TheSinding** [comment] 2020-06-19 07:46
@claustres I can do that, but right now I'm in the middle of moving and increased workload from my job, but I'll give it a look around the 5th ?

**Comment by OnnoGabriel** [comment] 2020-06-19 08:07
@claustres, great news indeed! I can test it in our app, although we are not using all of the functionality of this package (just e-mail verification and password request/reset). On which branch?

**Comment by claustres** [comment] 2020-06-19 08:10
@OnnoGabriel master
@TheSinding you do what you can, no problem ;-) If not possible soon I will try to release anyway

**Comment by TheSinding** [comment] 2020-06-19 08:16
@claustres - I just ran the tests on my machine, from the master, and I can confirm that it works.

**Comment by OnnoGabriel** [comment] 2020-06-19 08:53
@claustres, all tests on my mache run through, too. 

Next, I installed the master branch from this repo in our app, created a new user, verified its email address and performed a password request/reset. All fine!

**Comment by claustres** [comment] 2020-06-19 08:54
Great, will try to release then.

**Comment by claustres** [comment] 2020-06-24 07:41
Just published a new major release (v3.0.0) on npm, let me know if it works fine on your side.

**Comment by TheSinding** [comment] 2020-06-24 07:49
I'll try it later! :tada:

**Comment by claustres** [comment] 2020-06-24 07:58
I've just tested in our apps and it has broken some tests, I am afraid that migrating toward v4 has probably broken v3 support at the same time (we don't yet use v4 in our apps), don't know if we can easily support both of it.

One error I get is about this [line](https://github.com/feathersjs/feathers/blob/master/packages/authentication-local/src/hooks/hash-password.ts#L33): `TypeError: app.defaultAuthentication is not a function`.

**Comment by claustres** [comment] 2020-06-24 08:13
@TheSinding @OnnoGabriel What are your npm usernames so that I can give you access as well ? Thanks

**Comment by TheSinding** [comment] 2020-06-24 08:15
@claustres [thesinding](https://www.npmjs.com/~thesinding)

**Comment by OnnoGabriel** [comment] 2020-06-24 08:36
@claustres [onnogeorg](https://www.npmjs.com/~onnogeorg) (but not very active on npm).

I will also test it in our Feathers v3 app. Probably on Friday.

**Comment by OnePunchMan007** [comment] 2020-06-25 01:59
Thanks it's working for me in V4 app

**Comment by astralmedia** [comment] 2020-08-05 16:19
I have updated to the 3.0.0 FAM package, but I still get the same errors...Am I missing something? Thanks for any feedback
